### ISSUE TITLE
`onFrameChange()` is very inefficient in combination with `goToFrame(0)`

### ISSUE THREAD

**Issue by Dan503** [pixfabrik/driftory-viewer#12]
In `src/demo/demo.ts` add `console.log({ frameIndex })` to the `onFrameChange` function.

![code sample](https://user-images.githubusercontent.com/10610368/96325305-85151680-1072-11eb-9be2-6a3c246983e3.png)

Open the browser console and jump forward a few frames.

Now press the "start" button and watch what gets logged to the console.

![Clicking start triggers on frame change for every frame it passes](https://user-images.githubusercontent.com/10610368/96325383-07053f80-1073-11eb-86a1-41fae39b3538.png)

Note that `onFrameChange` gets called for every single frame it passes on it's way to it's destination. This is highly inefficient and not expected behavior.

`onFrameChange` should only get called once it has reached its final destination.

I think this issue might be what is causing #9 for me.

**Comment by iangilman** [comment]
Good point! I shall fix…

**Comment by iangilman** [comment]
Okay, this should be fixed now by #14!
