### ISSUE TITLE
Need a way to temporarily disable Driftory navigation

### ISSUE THREAD

**Issue by Dan503** [pixfabrik/driftory-viewer#18]
When the user reaches the end of a comic, I'm going to be presenting a dialog window over the top asking them things like contributing to Patreon and fill in their email address to subscribe to a newsletter.

While they are filling in their email address, if they press the left/right arrow keys to re-position the cursor, I don't want the Driftory comic to be shifting between frames in the background.

I still want the comic to be visible in the background though so I just want to be able to temporarily disable the navigation controls while the dialog is open.

**Comment by iangilman** [comment]
Fixed with https://github.com/pixfabrik/driftory-viewer/pull/20
