### ISSUE TITLE
Driftory viewer needs to be able to load a second comic in the same viewer instance

### ISSUE THREAD

**Issue by Dan503** [pixfabrik/driftory-viewer#25]
I have this react code:

```js
	React.useEffect(() => {
		if (comicData && driftory) {
			driftory.openComic(comicData)
			driftory.goToFrame(0)
		}
	}, [comicData, driftory])
```

When the user clicks to go to the next chapter, React runs this code with a new value for `comicData`

I get this error though:

> Currently the Driftory viewer is not set up to load a second comic after the first.

I need this functionality in order to let the user proceed to the next chapter in the comic sequence though.

**Comment by iangilman** [comment]
Cool... just a corner I cut early so we could get something running. All fixed up now :)
