### ISSUE TITLE
Can images please fade in?

### ISSUE THREAD

**Issue by Dan503** [pixfabrik/driftory-viewer#31]
When the edit screen is load each image fades in one at a time as they loaded. This is a nice effect.

When viewing the comic, images never fade in. This is a very jarring experience that detracts from the experience of reading the comics.

When viewing a comic, the comic should fade in both when it loads and when it hits the "don't show until frame" threshold.

**Comment by iangilman** [comment]
Agreed… I've been meaning to get to this; thank you for filing an issue :-)

**Comment by Dan503** [comment]
Can you also make the fade in speed a bit faster? It feels really slow at the moment.

0.5 seconds is a good fade in speed. Slow enough to convey the feeling of fading in but fast enough to not frustrate the user with how long the fade in takes to finish animating.
