### ISSUE TITLE
Incompatibility issues with @reach/router

### ISSUE THREAD

**Issue by Dan503** [pixfabrik/driftory-viewer#32]
I'm using Gatsby and Gatsby uses `@reach/router` for handling routing.

What I'm trying to do is have the URL update as the user navigates around comic panels so that if they send the link to a friend, their friend is immediately taken to that specific comic panel. users could then also bookmark the panel they are up to and continue reading later.

When I use the [useNavigate](https://reach.tech/router/api/useNavigate) feature in `@reach/router` I get the following message and it acts as if it reloads the entire comic.

> Ignoring tile 0/0_0 loaded before reset: http://localhost/wp_BIC/wp-content/uploads/2020/09/Panel-1-bg.png

The message is coming from openseadragon.

I can see that this is not going to be easy to test. I could give you access to my codebase if you want.

**Comment by iangilman** [comment]
Interesting. That does sound like it's reloading the comic. Yeah, taking a look at the code base might help, or at least if you could share the applicable bits.

**Comment by iangilman** [comment]
Or if you have a deployed version I could look at? If so, email me the link or something, since this issue here is public.

**Comment by Dan503** [comment]
I'll create a ticket in JIRA for you and give you access to the codebase.

**Comment by Dan503** [comment]
This was a problem on my end. I wasn't checking if the data had changed when calling `driftoryViewer.openComic(comicData)`
