### ISSUE TITLE
Allow custom fade animation duration

### ISSUE THREAD

**Issue by Dan503** [pixfabrik/driftory-viewer#39]
The current animation takes 1 full second to complete.

This is an extremely slow animation time. I think the default speed should be set to 500ms which generally strikes a good balance between speediness and ability to actually see the animation. 

300ms can also often work well though I think 500ms is better in this circumstance due to the size of the elements being animated. 300ms usually looks better on smaller animations.

Different comics might want different fade speeds with action comics preferring fast transitions and thoughtful/horror comics perhaps favoring slower fade animations.

Ideally it would be good to be able to set these animation speeds in the Driftory editor on individual frames. Different frames might require different transition speeds to get the right sort of feel for that particular scene in the comic. That is a bit out of scope for this ticket though.

For now I would be happy with just having the ability to set the general fade in speed for images using the Driftory Viewer API.

If nothing else, I'd like the default fade in speed to be changed to 0.5s. The 1s fade feels like an eternity.

**Comment by iangilman** [comment]
Yes, being able to customize this would be good!
