### ISSUE TITLE
Calling `goToFrame(0)` on last frame doesn't go to start

### ISSUE THREAD

**Issue by Dan503** [pixfabrik/driftory-viewer#9]
I'm trying to have it go back to the start when the user closes the Driftory viewer but when I call `goToFrame(0)` it only seems to go back one frame instead of going back to the start.

**Comment by iangilman** [comment]
I've added a "start" button to the demo in order to test this (in https://github.com/pixfabrik/driftory-viewer/pull/11). It's working for me. Is it still broken for you?

**Comment by Dan503** [comment]
It might have something to do with the specific scenario I'm using it in. I'm wondering if there is a problem when trying to go to a frame while the viewer isn't visible.

I'll try and replicate the issue in the demo.

**Comment by Dan503** [comment]
I added a hide/show button to the demo to test that it wasn't an issue with trying to navigate while the viewer is hidden.

I wasn't able to replicate the issue in the demo so it must be an issue in my code somewhere.
